dateModified: 1547075717
email:
  fromEmail: vadim@owl-design.net
  fromName: 'Craft 3 Starter'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  96d4c7cc-a76d-40bd-b07d-788ddea88e8f:
    name: Common
siteGroups:
  633a50f3-2f06-4ecc-8a12-7d62524ed208:
    name: 'Craft 3 Starter'
sites:
  74e52209-a5cc-4e52-82cd-3b1530cf89d2:
    baseUrl: '@web/'
    handle: default
    hasUrls: '1'
    language: en-US
    name: 'Craft 3 Starter'
    primary: '1'
    siteGroup: 633a50f3-2f06-4ecc-8a12-7d62524ed208
    sortOrder: '1'
system:
  edition: pro
  live: true
  name: 'Craft 3 Starter'
  schemaVersion: 3.1.12
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
